Scalars

In [2]:
x= 5
print("A scalar is just a single number",x)

A scalar is just a single number 5


Vectors - A vector is like an arrow - it has magnitude(lenght) and direction

In [7]:
import numpy as np
v= np.array([3,4]) # this is a 2D vector (x=3, y=4) - like pointing from (0,0) to (3,4)

To find how long the arrow is

In [8]:
length = np.linalg.norm(v)
print(length) # sqrt(3^2 + 4^2) = 5

5.0


Matrices - A matrix is like a table of numbers

In [9]:
matrix= np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


Dot product (Vector Multiplication)

In [13]:
a = np.array([1,2])
b= np.array([3,4])
dot_product= np.dot(a,b) # 1*3+2*4= 11
print(dot_product)

11


Matrix Multiplication

In [15]:
A = np.array ([[1,2],[3,4]])
B = np.array ([[5,6],[7,8]])
result = np.dot(A,B)
print(result)

[[19 22]
 [43 50]]


Example

In [16]:


v1 = np.array([2, 3])
v2 = np.array([1, 4])
v3 = np.array([5, 6])

# Lengths
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))
print(np.linalg.norm(v3))

# Dot product
print(np.dot(v1, v2))

# Combine into matrix
all_vectors = np.array([v1, v2, v3])
print(all_vectors)


3.605551275463989
4.123105625617661
7.810249675906654
14
[[2 3]
 [1 4]
 [5 6]]
